services:
  web:
    build: .
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - static_volume:/static
      - media_volume:/media
      - ./prod.nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: