services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-debug
    volumes:
      #- .:/app/    
      #- static_volume:/app/static
      #- media_volume:/app/media
      #- ./whale:/app/whale
      - ./whale:/app/whale
    expose:
      - "8000"
    ports:
      - "80:8000"
      - "5678:5678"
