version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: sqlite3
    environment:
      SQLITE3_DB: mydb
      SQLITE3_USER: myuser
      SQLITE3_PASSWORD: mypassword

