services:
  web:
    build: .
    #volumes:
    #  - static_volume:/app/static
    #  - media_volume:/app/media
    #  - ./animal:/app/animal
    expose:
      - "8000"
    ports:
      - "80:8000"
    command: ${BUILT_IN_SERVER_CMD:-/bin/bash -c "source activate gaia && gunicorn gaia.wsgi:application --bind 0.0.0.0:8000"}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  celery:
    build: .
    command: /bin/bash -c "source activate gaia && celery -A gaia worker -l info"
    depends_on:
      - redis
    volumes:
      - ./:/app
    environment:
      - DJANGO_SETTINGS_MODULE=gaia.settings

  celery-beat:
    build: .
    command: /bin/bash -c "source activate gaia && celery -A gaia beat -l info"
    depends_on:
      - redis
    volumes:
      - ./:/app
    environment:
      - DJANGO_SETTINGS_MODULE=gaia.settings

volumes:
  redis_data:
