services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-debug
      args:
        UID: ${UID}
        GID: ${GID}
        USER: ${USER}
        GROUP: ${GROUP}
    env_file:
      - .env
    volumes:
      - .:/app
    expose:
      - "8000"
    ports:
      - "80:8000"
      # pydebug listen port
      - "5678:5678"
