services:
  web:
    build: .
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    expose:
      - "8000"
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - static_volume:/static
      - media_volume:/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
