name: gaia
channels:
  - conda-forge
  - defaults
dependencies:
  - openssl=3.3.*        # Ensures compatibility with libgdal-core
  - libgdal=3.9.1 
  - django
  - psycopg2
  - affine
  - amqp
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow
  - asgiref
  - asttokens
  - async-lru
  - attrs
  - azure-core
  - azure-core-cpp
  - azure-identity
  - azure-identity-cpp
  - azure-storage-blob
  - azure-storage-blobs-cpp
  - azure-storage-common-cpp
  - babel
  - backports.zoneinfo
  - beautifulsoup4
  - billiard
  - blas
  - bleach
  - blosc
  - boto3
  - botocore
  - branca
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cached-property
  - cached_property
  - cairo
  - celery
  - certifi
  - cffi
  - cfitsio
  - charset-normalizer
  - click
  - click-didyoumean
  - click-plugins
  - click-repl
  - cligj
  - colorama
  - comm
  - contourpy
  - cpython
  - cryptography>=43.0.1
  - cycler
  - debugpy
  - decorator
  - debugpy
  - defusedxml
  - django
  - django-picklefield
  - django-q2
  - django-debug-toolbar
  - entrypoints
  - pip:
    - django-admin-sortable2
  - exceptiongroup
  - executing
  - expat
  - filelock
  - fiona
  - fmt
  - folium
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - fqdn
  - freetype
  - freexl
  - fsspec
  - gdal
  - geopandas
  - geopandas-base
  - geos
  - geotiff
  - git
  - h11>=0.16.0
  - h2
  - hdf4
  - hdf5
  - hpack
  - httpcore
  - httpx
  - hyperframe
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - intel-openmp
  - ipykernel
  - ipython
  - isodate
  - isoduration
  - jedi
  - jinja2>=3.1.6
  - jmespath
  - joblib
  - json5
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jsonschema-with-format-nongpl
  - jupyter-lsp
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - kealib
  - kiwisolver
  - kombu
  - krb5
  - lcms2
  - lerc
  - libabseil
  - libaec
  - libarchive
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcrc32c
  - libcurl
  - libdeflate
  - libexpat
  - libffi
  - libgdal-core
  - libgdal-fits
  - libgdal-grib
  - libgdal-hdf4
  - libgdal-hdf5
  - libgdal-jp2openjpeg
  - libgdal-kea
  - libgdal-netcdf
  - libgdal-pdf
  - libgdal-pg
  - libgdal-postgisraster
  - libgdal-tiledb
  - libgdal-xls
  - libglib
  - libgoogle-cloud
  - libgoogle-cloud-storage
  - libgrpc
  - libhwloc
  - libiconv
  - libjpeg-turbo
  - libkml
  - liblapack
  - libnetcdf
  - libpng
  - libpq
  - libprotobuf
  - libre2-11
  - librttopo
  - libsodium
  - libspatialite
  - libsqlite
  - libssh2
  - libtiff
  - libuv
  - libwebp-base
  - libxcb
  - libxml2
  - libxslt
  - libzip
  - libzlib
  - lz4-c
  - lzo
  - mapclassify
  - markupsafe
  - matplotlib-base
  - matplotlib-inline
  - minizip
  - mistune
  - mkl
  - mkl-service
  - mpmath>=1.3.0
  - msal
  - msal_extensions
  - munkres
  - nbclient
  - nbconvert-core
  - nbformat
  - nest-asyncio
  - networkx
  - notebook
  - notebook-shim
  - numpy
  - openjpeg
  - openssl
  - overrides
  - packaging
  - pandas
  - pandocfilters
  - parso
  - pcre2
  - pickleshare
  - pillow
  - pip>=5.1.4
  - pixman
  - pkgutil-resolve-name
  - platformdirs
  - poppler
  - poppler-data
  - portalocker
  - postgresql
  - proj
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - psycopg2
  - pthread-stubs
  - pure_eval
  - pycparser
  - pygments
  - pyjwt
  - pyogrio
  - pyparsing
  - pyproj
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python-tzdata
  - python_abi
  - pytorch
  - pytz
  - pywin32
  - pyyaml
  - pyzmq
  - qhull
  - rasterio
  - re2
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rpds-py
  - s3transfer
  - scikit-learn
  - scipy
  - send2trash
  - setuptools>=78.1.1
  - shapely
  - six
  - snappy
  - sniffio
  - snuggs
  - soupsieve
  - spdlog
  - sqlite
  - sqlparse
  - stack_data
  - sympy
  - tbb
  - terminado
  - threadpoolctl
  - tiledb
  - tinycss2
  - tk
  - tomli
  - tornado>=6.5
  - tqdm
  - traitlets
  - types-python-dateutil
  - typing-extensions
  - typing_extensions
  - typing_utils
  - tzdata
  - uri-template
  - uriparser
  - urllib3
  - vine
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - wheel
  - xerces-c
  - xorg-libxau
  - xorg-libxdmcp
  - xyzservices
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstandard
  - zstd
