# Generated by Django 5.0.7 on 2024-08-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthexplorer',
            name='date_entered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earthexplorer',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
