# Generated by Django 5.0.7 on 2024-08-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0002_alter_earthexplorer_date_entered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthexplorer',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
