# Generated by Django 5.0.7 on 2024-08-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0003_alter_earthexplorer_acquisition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthexplorer',
            name='pixel_size_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='earthexplorer',
            name='pixel_size_y',
            field=models.FloatField(),
        ),
    ]
