# Generated by Django 5.0.7 on 2024-08-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0004_alter_earthexplorer_pixel_size_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthexplorer',
            name='sun_elevation',
            field=models.FloatField(),
        ),
    ]
