# Generated by Django 5.0.7 on 2024-08-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0005_alter_earthexplorer_sun_elevation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geointdiscovery',
            name='acquisition_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='geointdiscovery',
            name='ingest_date',
            field=models.DateField(),
        ),
    ]
