# Generated by Django 5.0.7 on 2024-08-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0006_alter_geointdiscovery_acquisition_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geointdiscovery',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
