# Generated by Django 5.0.7 on 2024-09-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0007_alter_geointdiscovery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsofinterest',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='deviation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointsofinterest',
            name='catalog_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddConstraint(
            model_name='pointsofinterest',
            constraint=models.UniqueConstraint(fields=('id', 'catalog_id', 'vendor_id', 'entity_id'), name='fk_img_id'),
        ),
    ]
