# Generated by Django 5.0.7 on 2024-09-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0008_pointsofinterest_area_pointsofinterest_deviation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsofinterest',
            name='epsg',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
