# Generated by Django 5.0.7 on 2024-09-26 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0009_pointsofinterest_epsg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointsofinterest',
            old_name='epsg',
            new_name='epsg_code',
        ),
    ]
