# Generated by Django 5.0.7 on 2024-09-27 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0011_pointsofinterest_locked_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='reviewed_by',
            field=models.ManyToManyField(blank=True, related_name='reviewed_species', to=settings.AUTH_USER_MODEL),
        ),
    ]
