# Generated by Django 5.0.7 on 2024-09-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0012_remove_pointsofinterest_reviewed_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointsofinterest',
            old_name='reviewed_by',
            new_name='reviewed_by_users',
        ),
    ]
