# Generated by Django 5.1.6 on 2025-02-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0013_rename_reviewed_by_pointsofinterest_reviewed_by_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsofinterest',
            name='final_review',
            field=models.CharField(blank=True, choices=[('water', 'Water'), ('cloud', 'Cloud'), ('bird', 'Bird'), ('waves', 'Waves'), ('plane', 'Plane'), ('ship', 'Ship'), ('shadow', 'Shadow'), ('oil', 'Oil'), ('aquaculture', 'Aquaculture'), ('debris', 'Debris'), ('rock', 'Rock'), ('mudflats_or_land', 'Mudflats or Water'), ('buoy', 'Buoy'), ('whale', 'Whale'), ('zooplankton', 'Zooplankton'), ('land', 'Land'), ('unsure', 'Unsure')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='final_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='user1_classification',
            field=models.CharField(blank=True, choices=[('water', 'Water'), ('cloud', 'Cloud'), ('bird', 'Bird'), ('waves', 'Waves'), ('plane', 'Plane'), ('ship', 'Ship'), ('shadow', 'Shadow'), ('oil', 'Oil'), ('aquaculture', 'Aquaculture'), ('debris', 'Debris'), ('rock', 'Rock'), ('mudflats_or_land', 'Mudflats or Water'), ('buoy', 'Buoy'), ('whale', 'Whale'), ('zooplankton', 'Zooplankton'), ('land', 'Land'), ('unsure', 'Unsure')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='user1_comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='user1_confidence',
            field=models.CharField(blank=True, choices=[('possible', 'Possible ( ≤ 75% )'), ('probable', 'Probable ( 75 - 85% )'), ('definite', 'Definite ( ≥ 85% )')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='user1_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='user1_species',
            field=models.CharField(blank=True, choices=[('unknown', 'Unkown'), ('right', 'Right'), ('humpback', 'Humpback'), ('fin', 'Fin'), ('sei', 'Sei'), ('minke', 'Minke'), ('beluga', 'Beluga'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='user2_classification',
            field=models.CharField(blank=True, choices=[('water', 'Water'), ('cloud', 'Cloud'), ('bird', 'Bird'), ('waves', 'Waves'), ('plane', 'Plane'), ('ship', 'Ship'), ('shadow', 'Shadow'), ('oil', 'Oil'), ('aquaculture', 'Aquaculture'), ('debris', 'Debris'), ('rock', 'Rock'), ('mudflats_or_land', 'Mudflats or Water'), ('buoy', 'Buoy'), ('whale', 'Whale'), ('zooplankton', 'Zooplankton'), ('land', 'Land'), ('unsure', 'Unsure')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='user2_comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='user2_confidence',
            field=models.CharField(blank=True, choices=[('possible', 'Possible ( ≤ 75% )'), ('probable', 'Probable ( 75 - 85% )'), ('definite', 'Definite ( ≥ 85% )')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='user2_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='user2_species',
            field=models.CharField(blank=True, choices=[('unknown', 'Unkown'), ('right', 'Right'), ('humpback', 'Humpback'), ('fin', 'Fin'), ('sei', 'Sei'), ('minke', 'Minke'), ('beluga', 'Beluga'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='user3_classification',
            field=models.CharField(blank=True, choices=[('water', 'Water'), ('cloud', 'Cloud'), ('bird', 'Bird'), ('waves', 'Waves'), ('plane', 'Plane'), ('ship', 'Ship'), ('shadow', 'Shadow'), ('oil', 'Oil'), ('aquaculture', 'Aquaculture'), ('debris', 'Debris'), ('rock', 'Rock'), ('mudflats_or_land', 'Mudflats or Water'), ('buoy', 'Buoy'), ('whale', 'Whale'), ('zooplankton', 'Zooplankton'), ('land', 'Land'), ('unsure', 'Unsure')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='user3_comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='user3_confidence',
            field=models.CharField(blank=True, choices=[('possible', 'Possible ( ≤ 75% )'), ('probable', 'Probable ( 75 - 85% )'), ('definite', 'Definite ( ≥ 85% )')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='user3_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='user3_species',
            field=models.CharField(blank=True, choices=[('unknown', 'Unkown'), ('right', 'Right'), ('humpback', 'Humpback'), ('fin', 'Fin'), ('sei', 'Sei'), ('minke', 'Minke'), ('beluga', 'Beluga'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pointsofinterest',
            name='classification',
            field=models.CharField(choices=[('water', 'Water'), ('cloud', 'Cloud'), ('bird', 'Bird'), ('waves', 'Waves'), ('plane', 'Plane'), ('ship', 'Ship'), ('shadow', 'Shadow'), ('oil', 'Oil'), ('aquaculture', 'Aquaculture'), ('debris', 'Debris'), ('rock', 'Rock'), ('mudflats_or_land', 'Mudflats or Water'), ('buoy', 'Buoy'), ('whale', 'Whale'), ('zooplankton', 'Zooplankton'), ('land', 'Land'), ('unsure', 'Unsure')], default='Unclassified', max_length=20),
        ),
    ]
