# Generated by Django 5.1.6 on 2025-02-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0014_pointsofinterest_final_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsofinterest',
            name='final_confidence',
            field=models.CharField(blank=True, choices=[('possible', 'Possible ( ≤ 75% )'), ('probable', 'Probable ( 75 - 85% )'), ('definite', 'Definite ( ≥ 85% )')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='final_species',
            field=models.CharField(blank=True, choices=[('unknown', 'Unkown'), ('right', 'Right'), ('humpback', 'Humpback'), ('fin', 'Fin'), ('sei', 'Sei'), ('minke', 'Minke'), ('beluga', 'Beluga'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
