# Generated by Django 5.1.6 on 2025-03-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0015_pointsofinterest_final_confidence_and_more'),
    ]

    operations = [
        migrations.RunSQL(
             """
            CREATE TRIGGER update_final_review
            AFTER UPDATE ON whale_pointsofinterest
            FOR EACH ROW
            WHEN (
                NEW.user1_classification IS NOT NULL AND 
                NEW.user2_classification IS NOT NULL AND 
                NEW.user3_classification IS NOT NULL
            )
            BEGIN
                UPDATE whale_pointsofinterest
                SET final_review = CASE
                    WHEN NEW.user1_classification = 'whale' 
                         AND NEW.user2_classification = 'whale'
                         AND NEW.user3_classification = 'whale'
                    THEN 'whale'
                    WHEN NEW.user1_classification != 'whale' 
                         AND NEW.user2_classification != 'whale'
                         AND NEW.user3_classification != 'whale'
                    THEN 'not a whale'
                    END,
                    final_review_date = CASE
                        WHEN (
                            NEW.user1_classification = 'whale' AND 
                            NEW.user2_classification = 'whale' AND 
                            NEW.user3_classification = 'whale'
                        ) OR (
                            NEW.user1_classification != 'whale' AND 
                            NEW.user2_classification != 'whale' AND 
                            NEW.user3_classification != 'whale'
                        )
                        THEN date('now')
                        END
                WHERE id = NEW.id;
            END;
            """,
            reverse_sql="DROP TRIGGER IF EXISTS update_final_review;"
        ),
    ]
