# Generated by Django 5.2 on 2025-05-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0016_add_final_review_trigger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dummy',
        ),
    ]
