# Generated by Django 5.2 on 2025-05-12 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0017_delete_dummy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classification_value', models.CharField(max_length=25)),
                ('classification_label', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Confidence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('confidence_value', models.CharField(max_length=10)),
                ('confidence_label', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Annotations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whale.pointsofinterest')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whale.classification')),
                ('confidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whale.confidence')),
            ],
        ),
    ]
