# Generated by Django 5.2 on 2025-05-12 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0018_classification_confidence_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whale.targets'),
        ),
    ]
