# Generated by Django 5.2 on 2025-05-13 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0019_annotations_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotations',
            name='confidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whale.confidence'),
        ),
        migrations.AlterField(
            model_name='annotations',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whale.targets'),
        ),
    ]
