# Generated by Django 5.2.1 on 2025-05-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0020_alter_annotations_confidence_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classification',
            new_name='Classifications',
        ),
        migrations.RenameField(
            model_name='classifications',
            old_name='classification_value',
            new_name='classification',
        ),
    ]
