# Generated by Django 5.2.1 on 2025-05-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0021_rename_classification_classifications_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classifications',
            new_name='Classification',
        ),
    ]
