# Generated by Django 5.2.1 on 2025-05-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0022_rename_classifications_classification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confidence',
            old_name='confidence_value',
            new_name='confidence',
        ),
    ]
