# Generated by Django 5.2.1 on 2025-05-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0023_rename_confidence_value_confidence_confidence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification',
            old_name='classification',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='classification',
            old_name='classification_label',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='confidence',
            old_name='confidence_label',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='confidence',
            old_name='confidence',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='targets',
            old_name='target',
            new_name='value',
        ),
    ]
