# Generated by Django 5.2.1 on 2025-05-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0024_rename_classification_classification_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification',
            old_name='label',
            new_name='label2',
        ),
        migrations.RenameField(
            model_name='classification',
            old_name='value',
            new_name='value2',
        ),
    ]
