# Generated by Django 5.2.1 on 2025-05-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0025_rename_label_classification_label2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification',
            old_name='value2',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='classification',
            old_name='label2',
            new_name='value',
        ),
    ]
