# Generated by Django 5.2.1 on 2025-05-14 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0026_rename_value2_classification_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasking',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveConstraint(
            model_name='pointsofinterest',
            name='fk_img_id',
        ),
        migrations.RenameField(
            model_name='targets',
            old_name='scientific_name',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='client_ip',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='final_confidence',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='final_review',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='in_time',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='locked_by',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='out_time',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='reviewed_by_users',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='species',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='user1_classification',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='user1_comments',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='user1_confidence',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='user1_id',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='user1_species',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='user2_classification',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='user2_comments',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='user2_confidence',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='user2_id',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='user2_species',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='user3_classification',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='user3_comments',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='user3_confidence',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='user3_id',
        ),
        migrations.RemoveField(
            model_name='pointsofinterest',
            name='user3_species',
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='cog_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='final_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whale.classification'),
        ),
        migrations.AlterField(
            model_name='pointsofinterest',
            name='final_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whale.targets'),
        ),
        migrations.AlterField(
            model_name='pointsofinterest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
