# Generated by Django 5.2.1 on 2025-05-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0027_alter_tasking_requestor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotations',
            old_name='user_id',
            new_name='user',
        ),
    ]
