name: CI Test

on:
  push:
    branches:
      - test
  workflow_dispatch:

env:
  APPNAME: gaia-test
  REGISTRY: ghcr.io
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
        id-token: write

    steps:
    - name: Generate build ID
      id: prep
      run: |
        branch=${GITHUB_REF##*/}
        branch=${branch,,}  # Convert to lowercase for Azure revision syntax
        branch=${branch//[^a-z0-9\-]/-}  # Replace invalid characters with hyphens
        echo "branch=${branch}"
        sha=${GITHUB_SHA::8}
        ts=$(date +%s)
        reponame="${GITHUB_REPOSITORY,,}"
        echo "BUILD_ID=${branch}-${sha}-${ts}" >> $GITHUB_OUTPUT
        echo "LOWER_NAME=${reponame}" >> $GITHUB_OUTPUT
        echo "LOWER_NAME=${reponame}"
        echo "GIT_BRANCH=${GITHUB_HEAD_REF:-${branch}}" >> $GITHUB_OUTPUT
        echo "GIT_BRANCH=${GITHUB_HEAD_REF:-${branch}}"

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ steps.prep.outputs.LOWER_NAME }}:${{ steps.prep.outputs.BUILD_ID }}
        build-args: |
          GITHUB_OAUTH_TOKEN=${{ secrets.CICDTOKEN }}

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Update Azure Container App
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          LATEST_REVISION=$(az containerapp update \
            --name ${{ env.APPNAME }} \
            --resource-group gaia-application-resource-group \
            --image ${{ env.REGISTRY }}/${{ steps.prep.outputs.LOWER_NAME }}:${{ steps.prep.outputs.BUILD_ID }} \
            --query 'properties.latestRevisionName')
          echo "Latest revision: $LATEST_REVISION"
          echo "REVISION=$LATEST_REVISION" >> $GITHUB_ENV

    - name: Label Azure Container App
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az containerapp revision label add \
            --revision ${{ env.REVISION }} \
            --resource-group gaia-application-resource-group \
            --label ${{ steps.prep.outputs.GIT_BRANCH }} \
            --verbose \
            --no-prompt
